Collection view
ThanyaniDev/MarsMission pull request #3
Opened 2020-11-09 05:43 UTC by ThanyaniDev

I have added an updated collection view screen
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-09 at 07 41 23](https://user-images.githubusercontent.com/55865505/98504173-f9506d80-225e-11eb-8138-6e8b3b5ae5b6.png)
And I have also added functions that convert UTC to Local Date
<img width="532" alt="Screenshot 2020-11-09 at 07 35 43" src="https://user-images.githubusercontent.com/55865505/98504223-200ea400-225f-11eb-9d6e-44f06dd424e0.png">

2020-11-09 10:52 UTC, Sashen943 requested changes
Please book some time with me to understand how collection views and arrays work

2020-11-09 10:52 UTC, Sashen943 commented on MarsMission/Controllers/LandingViewController.swift
> +		cell.dateLabel.text = "weather"
Remove these hard coded values

2020-11-09 10:52 UTC, Sashen943 commented on MarsMission/Controllers/LandingViewController.swift
> +		return 6
Should return the size of the array. Remove this hard coded 6

2020-11-09 10:52 UTC, Sashen943 commented on MarsMission/Models/WeatherData.swift
> +	var forecasts: [forecast]
class Forecast should be named with a capital. Remember that all classes in swift are named with a capital

2020-11-09 10:52 UTC, Sashen943 commented on MarsMission/Models/WeatherData.swift
> +struct forecast: Codable {
Capitalise class name

2020-11-09 10:52 UTC, Sashen943 commented on MarsMission/ViewModels/WeatherDataViewModel.swift
> +										  weatherData.weatherStation!,
Why do you have this function if you're using a collection view? Make sure to understand how arrays work

2020-11-09 10:52 UTC, Sashen943 commented on MarsMission/Views/WeatherView.swift
> +	func populateWeatherData(_ lastUpdated: String,_ weatherStation: String,_ date: String,_ temp: Double)
Why do you have this function if you're using a collection view? Please ensure that you understand how the UI Components that you are using works before you use them

2020-11-09 10:52 UTC, Sashen943 commented on MarsMission/Helper/UTCToDate.swift
> +	let localDateString =  format.string(from: convertedDate!)
Remove forceful unwrapping here

2020-11-09 10:52 UTC, Sashen943 commented on MarsMission/Controllers/LandingViewController.swift
> -		let nib = UINib(nibName: "weatherForecastViewCell", bundle: nil)
Why is you nib named with a lower case?

2020-11-11 04:13 UTC, ThanyaniDev commented
<img width="324" alt="Screenshot 2020-11-11 at 05 50 18" src="https://user-images.githubusercontent.com/55865505/98764397-63dee600-23e4-11eb-93e2-ad75197df025.png">
<img width="584" alt="Screenshot 2020-11-11 at 01 56 51" src="https://user-images.githubusercontent.com/55865505/98764439-73f6c580-23e4-11eb-863c-e3d603d44764.png">
Added Project Structure Changes and added nil coalescing

2020-11-11 05:49 UTC, ThanyaniDev commented
<img width="331" alt="Screenshot 2020-11-11 at 07 48 27" src="https://user-images.githubusercontent.com/55865505/98773815-65afa600-23f2-11eb-8783-2b24d3002ff0.png">

<img width="584" alt="Screenshot 2020-11-11 at 01 56 51" src="https://user-images.githubusercontent.com/55865505/98773852-74965880-23f2-11eb-8520-adafca5f4613.png">

2020-11-12 01:53 UTC, ThanyaniDev commented
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-12 at 03 50 53](https://user-images.githubusercontent.com/55865505/98885233-571cc980-249a-11eb-8eae-a132daf083dd.png)
Updated forecast View.
![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-12 at 03 51 00](https://user-images.githubusercontent.com/55865505/98885324-7d426980-249a-11eb-9ae7-286b36ace2bc.png)
forecast detail view

2020-11-13 10:31 UTC, Sashen943 approved these changes

2020-11-16 05:39 UTC, merged